#!/usr/bin/env bash
#Display info

display_info() {
    local domain=$1
    local sub_domain=$2
    local record_type=$(dig +short -t A $sub_domain.$domain | awk '{print length ? "A" : "CNAME"}')
    local destination=$(dig +short $sub_domain.$domain)

    echo "The subdomain $sub_domain is a $record_type record and points to $destination"
}

if [ $# -eq 1 ]; then
    display_info $1 www
    display_info $1 lb-01
    display_info $1 web-01
    display_info $1 web-02
elif [ $# -eq 2 ]; then
    display_info $1 $2
else
    echo "Usage: $0 <domain> [sub_domain]"
fi
