#!/usr/bin/env bash
# Docs

display_info() {
    local domain=$1
    local subdomain=$2
    local record_type=$(dig +short -t A $subdomain.$domain | awk '{print length ? "A" : "CNAME"}')
    local destination=$(dig +short $subdomain.$domain)

    echo "The subdomain $subdomain is a $record_type record and points to $destination"
}

if [ $# -eq 1 ]; then
    # Display information for default subdomains www, lb-01, web-01, and web-02
    display_info $1 www
    display_info $1 lb-01
    display_info $1 web-01
    display_info $1 web-02
elif [ $# -eq 2 ]; then
    # Display information for the specified subdomain
    display_info $1 $2
else
    echo "Usage: $0 <domain> [subdomain]"
fi
