#!/usr/bin/env bash
#install nginx in server and listen to file where it say Hello world
sudo apt-get update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
service nginx start
