#!/usr/bin/env bash
#install nginx in server and listen to file where it say Hello world
sudo apt-get update
sudo apt-get -y install nginx
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
redirect="\n\tlocation /redirect_me {\n\t\treturn 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;\n\t}\n"
sudo sed -i "53s|.*|$redirect|" /etc/nginx/sites-enabled/default
custom_404="\n\terror_page 404 /404.html;\n\tlocation = /404.html {\n\t\troot /usr/share/nginx/html;\n\t\tinternal;\n\t\techo 'Ceci n'est pas une page';\n\t}\n"
sudo sed -i "s|location / {|\0$custom_404|" /etc/nginx/sites-enabled/default
service nginx start

