#!/usr/bin/env bash
#install nginx in server and listen to file where it say Hello world
sudo apt-get update
sudo apt-get -y install nginx
custom_header="add_header X-Served-By \$hostname;"
sudo sed -i "/server_name _;/a \ \n\t$custom_header" /etc/nginx/sites-available/default
sudo service nginx start
