#!/usr/bin/env bash
#enable listining to site 80

sites="/etc/nginx/sites-enabled/default"

config="
server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	root /usr/share/nginx/html
	
	index index.html index.html;
	# Make site accessible from http://localhost/
	server_name localhost;

}
"
echo "$config" > sites
service nginx restart
