#!/usr/bin/env bash
#enable listining to site 80
sites="/etc/nginx/sites-enabled"

if ! grep -q -E "listen 80(;|$)" "$sites"/* && grep -q "listen 80[^0-9]" "$sites"/*; then
    sed -i '/server {/ a \        listen 80 default_server;' "$sites"/*
    sed -i '/server {/ a \        listen [::]:80 default_server;' "$sites"/*
    sed -i '/server {/ a \        root /var/www/html;' "$sites"/*
    sed -i '/server {/ a \        index.html index.htm index.nginx-debian.html;;' "$sites"/*
    sudo service nginx restart
    echo "done"
else echo "Port 80 configuration already exists."
fi
