#!/usr/bin/env bash
# nginx

sudo chmod 644 /etc/nginx/nginx.conf
sudo sed -Ei 's/\s#?\suser .*/user nginx;/' /etc/nginx/nginx.conf
sudo sed -i 's/listen 80/listen 8080/' /etc/nginx/sites-available/default
sudo sed -i 's/listen \[::\]:80 /listen [::]:8080 /' /etc/nginx/sites-available/default
pkill apache2
sudo service nginx restart
